@isTest
// Simple class and test class created to imporve Overall code coverage of the org as it was 67%
public class ex2Tesst {

    public static testmethod void ex2tesstmethod01(){
        ex2 e = new ex2();
        e.a = 2;
        e.b = 1;
        e.dis();
    }
    
    public static testmethod void ex2tesstmethod02(){
        ex2 e1 = new ex2();
         e1.a = 1;

        e1.b = 2;

        e1.dis();

    }
}